### ISSUE TITLE
[BUG] Version mismatch between OpenSearch, Dashboards, and prometheus-exporter plugin when using major version specifiers with monitoring enabled

### ISSUE THREAD

**Issue by jpulgar4** [opensearch-project/opensearch-k8s-operator#1235]
### What is the bug?

When using the OpenSearch Kubernetes Operator with monitoring enabled and a major version specifier (e.g., `version: "3"`), there is a version mismatch between the OpenSearch nodes, the prometheus-exporter plugin, and the Dashboards deployment that causes cascading failures.

**The issues:**

1. **Prometheus-exporter plugin version mismatch**: When `monitoring.enable: true` is set with a `pluginUrl` pointing to a specific plugin version (e.g., `3.3.2.0`), but OpenSearch auto-upgrades to a newer version (e.g., `3.4.0`), the plugin installation fails because the plugin version must exactly match the OpenSearch version.

2. **Dashboards version inconsistency**: When the cluster spec uses `version: "3"` for both OpenSearch and Dashboards, they may resolve to different actual versions. In our case, OpenSearch was pinned to `3.3.2` while Dashboards resolved to `3.4.0`, causing version incompatibility errors.

3. **No graceful handling**: The operator doesn't validate that the prometheus-exporter plugin version matches the OpenSearch version before attempting deployment, leading to crashlooping pods.

### How can one reproduce the bug?

1. Deploy an OpenSearchCluster with monitoring enabled:
```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
spec:
  general:
    version: "3.3.2"
    monitoring:
      enable: true
      scrapeInterval: 30s
      pluginUrl: https://github.com/opensearch-project/opensearch-prometheus-exporter/releases/download/3.3.2.0/prometheus-exporter-3.3.2.0.zip
      tlsConfig:
        insecureSkipVerify: true
  dashboards:
    enable: true
    version: "3"
```

2. Wait for OpenSearch to auto-upgrade to a version newer than the prometheus-exporter plugin (e.g., OpenSearch upgrades to `3.4.0` while plugin is `3.3.2.0`)

3. Observe pods crashlooping with plugin version mismatch errors

4. Pin OpenSearch to `3.3.2` to match the plugin, but leave Dashboards at `"3"`

5. Observe Dashboards failing due to version incompatibility with the OpenSearch cluster

### What is the expected behavior?

1. **Version validation**: The operator should validate that the prometheus-exporter plugin version matches the OpenSearch version before attempting to deploy, and provide a clear error message if there's a mismatch.

2. **Consistent version resolution**: When using major version specifiers like `"3"`, both OpenSearch and Dashboards should resolve to the same actual version to prevent inconsistencies.

3. **Graceful degradation**: If the prometheus-exporter plugin for the current OpenSearch version is not available, the operator should either:
   - Skip plugin installation and log a warning
   - Prevent the upgrade until a compatible plugin is available
   - Provide clear documentation about version pinning requirements

4. **Better defaults**: When `pluginUrl` is not specified, the operator should automatically determine the correct plugin URL based on the actual OpenSearch version being deployed.

### What is your host/environment?

- Kubernetes: EKS
- OpenSearch Operator: 2.9.0 (via Helm)
- OpenSearch: 3.3.2 → 3.4.0 (auto-upgraded)
- prometheus-exporter plugin: 3.3.2.0

### Do you have any screenshots?

_N/A_

### Do you have any additional context?

**Pod logs showing plugin version mismatch:**
```
-> Installing https://github.com/opensearch-project/opensearch-prometheus-exporter/releases/download/3.3.2.0/prometheus-exporter-3.3.2.0.zip
-> Downloading https://github.com/opensearch-project/opensearch-prometheus-exporter/releases/download/3.3.2.0/prometheus-exporter-3.3.2.0.zip
-> Failed installing https://github.com/opensearch-project/opensearch-prometheus-exporter/releases/download/3.3.2.0/prometheus-exporter-3.3.2.0.zip
-> Rolling back https://github.com/opensearch-project/opensearch-prometheus-exporter/releases/download/3.3.2.0/prometheus-exporter-3.3.2.0.zip
-> Rolled back https://github.com/opensearch-project/opensearch-prometheus-exporter/releases/download/3.3.2.0/prometheus-exporter-3.3.2.0.zip
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [prometheus-exporter] was built for OpenSearch version 3.3.2 but version 3.4.0 is running
        at org.opensearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:459)
        at org.opensearch.tools.cli.plugin.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:801)
        at org.opensearch.tools.cli.plugin.InstallPluginCommand.installPlugin(InstallPluginCommand.java:846)
        ...
```

**Attempting to pin OpenSearch to 3.3.2 after it already upgraded to 3.4.0:**
```
java.lang.IllegalStateException: cannot downgrade a node from version [3.4.0] to version [3.3.2]
        at org.opensearch.env.NodeMetadata.upgradeToCurrentVersion(NodeMetadata.java:106)
        at org.opensearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:503)
        ...
```

**Dashboards version incompatibility with OpenSearch cluster:**
```json
{
  "type": "log",
  "@timestamp": "2025-12-18T11:26:13Z",
  "tags": ["error", "savedobjects-service"],
  "pid": 1,
  "message": "This version of OpenSearch Dashboards (v3.4.0) is incompatible with the following OpenSearch nodes in your cluster: v3.3.2 @ opensearch-masters-1/10.8.37.26:9200 (10.8.37.26), v3.3.2 @ opensearch-masters-2/10.8.35.154:9200 (10.8.35.154), v3.3.2 @ opensearch-data-1/10.8.47.81:9200 (10.8.47.81), v3.3.2 @ opensearch-data-0/10.8.42.138:9200 (10.8.42.138), v3.3.2 @ opensearch-masters-0/10.8.45.62:9200 (10.8.45.62), v3.3.2 @ opensearch-data-2/10.8.37.23:9200 (10.8.37.23)"
}
```

**Workaround**: Pin both OpenSearch and Dashboards to a specific version (e.g., `version: "3.3.2"`) that matches the prometheus-exporter plugin version. However, this requires manual intervention and prevents automatic minor version updates. However there is a caveat, pinning the Dashboard's version to "3.3.2" is not possible due to the image tag 3.3.2 not being pushed to the repository. The only available image tag is "3" which resolves to 3.4.0 blocking the auto-upgrade anyways.

**Suggested improvements:**
1. Add version compatibility checks in the operator reconciliation loop
2. Document the version pinning requirements when using monitoring
3. Consider auto-detecting the correct prometheus-exporter plugin URL based on the actual OpenSearch version
4. Ensure Dashboards and OpenSearch versions stay in sync when using major version specifiers
5. When OpenSearch is pinned to a specific version, automatically pin Dashboards to the same version unless explicitly overridden

**Comment by synhershko** [comment]
Which operator versions did you use?

**Comment by jpulgar4** [comment]
@synhershko version `v2.8.0` of the [operator](https://github.com/opensearch-project/opensearch-k8s-operator)

**Comment by synhershko** [comment]
Can you try with the latest (master branch ; or wait for a pre-release of 3.0.0)? it should already be fixed or at least the exhibited behavior should be different

**Comment by synhershko** [comment]
@jpulgar4 can we close?

**Comment by jpulgar4** [comment]
@synhershko sorry not yet, I'm still unable to test with release 3.0.0 since it's not been published and we can't test on pre-release versions. I will rather wait until 3.0.0 is released and test there

**Comment by jpulgar4** [comment]
solved as tested with operator 3.0.2
