### ISSUE TITLE
[FR] OpenSearch Operator on OperatorHub.io

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-k8s-operator#70]
[OperatorHub.io](https://operatorhub.io/) is a new home for the Kubernetes community to share Operators. 

It would be great to see OpenSearch Operator make it to the OperatorHub.io so the OpenSearch Kubernetes user-base could discover it easily.

**Comment by segalziv** [comment]
Thanks @setiah , indeed we plan to publish the Operator in [OperatorHub.io](https://operatorhub.io/). The plan is for @idanl21 to finish with the release process, and then publish. I believe that the first release will be available around the next week.

**Comment by setiah** [comment]
Thanks for the details @segalziv. I couldn't find an issue so created one to track this :)

**Comment by idanl21** [comment]
Hey, we facing some problems in some of the operator actions, didnt had the chance to really work about it. hope to start it after first release in the end of the week.

**Comment by shahar35** [comment]
We created artifactHub project, located:
https://artifacthub.io/packages/helm/opensearch-operator/opensearch-operator?modal=install

**Comment by segalziv** [comment]
@setiah to summarize so far, we have implemented the same capability through artifacthub.io. We will keep this ticket open and might register the operator in operatorHub in the future as well, but for now it's in lower priority.

**Comment by prudhvigodithi** [comment]
Re-opening this issue as publish of OpenSearch Kubernetes Operator to [OperatorHub.io](https://operatorhub.io/) is still not yet completed. 
Adding @dbason @swoehrl-mw @jochenkressin @pchmielnik @salyh
@bbarani @rishabh6788

**Comment by prudhvigodithi** [comment]
Closing this issue as the OpenSearch operator is now in operatorhub https://operatorhub.io/operator/opensearch-operator.
@synhershko @josedev-union @patelsmit32123
